import { Teacher } from "../types";

export const teacherList: Teacher[] = [
	{
		id: "929",
		name: "Olivia Barnes",
		role: "Teacher",
		birthDate: "1988-12-04",
		email: "ihahn@saunders.com",
		phone: "418-247-9746",
		address: "570 Debbie Shoal Apt. 786, South Jeremy, PA 20624",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "120",
		name: "Thomas Young",
		role: "Teacher",
		birthDate: "1995-09-24",
		email: "xrussell@hotmail.com",
		phone: "203-618-8985x88583",
		address: "13127 Alvarez Gateway, North Michaelmouth, KY 23071",
		privateQualifications: [
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "687",
		name: "Ashley Carson",
		role: "Teacher",
		birthDate: "1991-11-13",
		email: "wfuller@smith.com",
		phone: "183-456-3328",
		address: "1268 Harold Viaduct, West Elizabethborough, AZ 92165",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "248",
		name: "Jeremy Norton",
		role: "Teacher",
		birthDate: "1992-03-17",
		email: "francisjulia@yahoo.com",
		phone: "317-988-9266",
		address: "391 Matthew Street Suite 102, Port Kimberly, MS 27053",
		privateQualifications: [],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
			{ name: "Choir Practice", rate: 18 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "874",
		name: "Isabella Morgan",
		role: "Teacher",
		birthDate: "1980-05-10",
		email: "kmeyer@carroll.com",
		phone: "239-494-7154",
		address: "200 Barnes Hollow, South Trevor, NJ 43693",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [],
	},
	{
		id: "503",
		name: "Nathaniel Thomas",
		role: "Teacher",
		birthDate: "1990-07-08",
		email: "zthomas@young.com",
		phone: "445-896-4520",
		address: "2634 Park Place Apt. 10, North Brenda, MN 16020",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "164",
		name: "Ava Hughes",
		role: "Teacher",
		birthDate: "1985-04-22",
		email: "canderson@hernandez.net",
		phone: "551-789-8036",
		address: "14955 Johnston Port, Port Tyler, MA 72531",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "735",
		name: "Sophia Robinson",
		role: "Teacher",
		birthDate: "1987-08-19",
		email: "andreahall@yahoo.com",
		phone: "716-574-2214",
		address: "35917 Boyd Divide, West Nancy, SD 12364",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
			{ name: "Choir Practice", rate: 18 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "645",
		name: "Henry Moore",
		role: "Teacher",
		birthDate: "1982-09-09",
		email: "shannonmoore@shaw.com",
		phone: "670-303-1123",
		address: "93734 Price Loop, Lake Erin, IA 53801",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [{ name: "Group Singing", rate: 20 }],
	},
	{
		id: "236",
		name: "Emily Simmons",
		role: "Teacher",
		birthDate: "1993-11-28",
		email: "emilysim@walker.net",
		phone: "882-448-3210",
		address: "42988 Megan Road, East Steven, NM 54062",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "459",
		name: "Lucas Bennett",
		role: "Teacher",
		birthDate: "1989-06-11",
		email: "lucasbennett@aol.com",
		phone: "312-432-7754",
		address: "354 Adams View, East Alexander, IL 60564",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "310",
		name: "Grace Adams",
		role: "Teacher",
		birthDate: "1986-02-17",
		email: "graceadams@live.com",
		phone: "478-909-1124",
		address: "1275 Stevens Way, South Steven, GA 30902",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "511",
		name: "Logan Wood",
		role: "Teacher",
		birthDate: "1991-03-25",
		email: "loganwood@gmail.com",
		phone: "512-672-3332",
		address: "5893 Coleman Path, North Lauren, TX 75025",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "122",
		name: "Ella Brooks",
		role: "Teacher",
		birthDate: "1983-10-14",
		email: "ellabrooks@yahoo.com",
		phone: "201-832-7741",
		address: "117 Andrew Plaza, Port Olivia, NJ 07094",
		privateQualifications: [],
		groupQualifications: [],
	},
	{
		id: "893",
		name: "Ethan James",
		role: "Teacher",
		birthDate: "1990-01-09",
		email: "ethanjames@cox.net",
		phone: "404-751-6631",
		address: "3083 Griffith Run, East Jacobport, GA 30301",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "266",
		name: "Aria Campbell",
		role: "Teacher",
		birthDate: "1984-07-05",
		email: "aria.campbell@edu.org",
		phone: "718-322-8012",
		address: "4530 Diaz Grove, North Justinburgh, NY 11219",
		privateQualifications: [],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "341",
		name: "Jack Turner",
		role: "Teacher",
		birthDate: "1987-12-22",
		email: "turnerjack@schoolmail.com",
		phone: "267-384-9163",
		address: "1297 Thompson Estates, East Elizabeth, PA 19422",
		privateQualifications: [{ name: "Vocal Core", rate: 30 }],
		groupQualifications: [{ name: "Choir Practice", rate: 18 }],
	},
	{
		id: "509",
		name: "Lily Evans",
		role: "Teacher",
		birthDate: "1992-06-18",
		email: "lily.evans@arts.com",
		phone: "713-544-6652",
		address: "4089 Marks Hollow, East Carter, TX 77002",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "778",
		name: "Noah Scott",
		role: "Teacher",
		birthDate: "1986-05-03",
		email: "noah.scott@vocalpro.net",
		phone: "845-373-9866",
		address: "7714 George Path, West Jasonland, NY 12401",
		privateQualifications: [{ name: "Vocal Core", rate: 30 }],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
	{
		id: "683",
		name: "Chloe Foster",
		role: "Teacher",
		birthDate: "1993-04-29",
		email: "cfoster@fostervocals.com",
		phone: "561-890-2458",
		address: "6710 Barrett Plain, North Tiffany, FL 33401",
		privateQualifications: [
			{ name: "Vocal Core", rate: 30 },
			{ name: "Vocal Contemporary", rate: 28 },
			{ name: "Instrument", rate: 32 },
		],
		groupQualifications: [
			{ name: "Group Singing", rate: 20 },
			{ name: "Choir Practice", rate: 18 },
		],
	},
];
